---
- hosts: r2
  gather_facts: true
  connection: local

  tasks:
   - name: config loopback0
     ios_config:
       commands:
         - interface loopback 1
         - ip address 2.2.2.2 255.255.255.255
         - router ospf 1
         - network 0.0.0.0 0.0.0.0 area 0
       host: "{{ ansible_host }}"
       username: cisco
       password: cisco
     register: config

