---
- name: Exec commands
  hosts: all
  gather_facts: false
  connection: network_cli


  tasks:
    - name: exec commands
      ios_command:
        commands:
          #- clear ip bgp *
          #- show cdp nei det
          - show run
          #- show ip route
          #- show ip eigrp neigh 
          #- show logging
          #- show ip bgp nei | inc Last read
          #- show ip route summ
      register: print_output1

    - debug: var=print_output1.stdout_lines

    #- name: save output to a file
    #  copy: content="{{ print_output1.stdout[0] }}" dest="./show_cmd_archive/{{ inventory_hostname }}_running_cfg.txt"

