---
- name: Push Configs to routers
  hosts: core-rtrs, distribution-rtrs, access-rtrs
  gather_facts: no
  connection: network_cli 

  tasks:
    - name: NetMgmt Configs
      ios_config:
        src: ./files/mgmt.j2
     
      register: output_netmgmt
    - debug: var=output_netmgmt


- name: Configure Login Banner
  connection: network_cli
  gather_facts: no
  hosts: all

  tasks:
    - ios_banner:
        banner: login
        text: |
          Attention - This is a lab. Under no circumstances are you to take this message seriously!

        state: present

- name: IGP config
  hosts: core-rtrs, distribution-rtrs, access-rtrs
  gather_facts: no
  connection: network_cli

  tasks:
    - name: IGP_Routing
      ios_config:
        src: ./files/{{inventory_hostname}}_igp_routing.j2

      register: output
    - debug: var=output


- name: Core BGP Routing
  hosts: core-rtrs
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Core-routers-bgp
      ios_config:
        src: ./files/{{inventory_hostname}}_bgp_neighbor_core

      register: output
    - debug: var=output



- name: Access Routers BGP config
  hosts: access-rtrs
  gather_facts: no
  connection: network_cli

  tasks:
    - name: access-rtrs-bgp-config
      ios_config:
        src: ./files/{{inventory_hostname}}_bgp_neighbor

      register: output
    - debug: var=output

- name: Access Routers BGP PBR config
  hosts: access-rtrs
  gather_facts: no
  connection: network_cli

  tasks:
    - name: access-rtrs_pbr
      ios_config:
        src: ./files/{{inventory_hostname}}_pbr

      register: output
    - debug: var=output

- name: Distribution Routers BGP config
  hosts: distribution-rtrs
  gather_facts: no
  connection: network_cli

  tasks:
    - name: distribution-rtrs-bgp-config
      ios_config:
        src: ./files/{{inventory_hostname}}_bgp_neighbor_dist

      register: output
    - debug: var=output


