---
- hosts: core-rtrs, distribution-rtrs, access-rtrs
  gather_facts: false
  connection: network_cli
  roles:
    - management

- hosts: r7
  gather_facts: false
  connection: network_cli
  vars_files: 
  - host_vars/r7
  roles:
    - routing
    - policy-based-rting

- hosts: r8
  gather_facts: false
  connection: network_cli
  vars_files:
  - host_vars/r8
  roles:
    - routing
    - policy-based-rting

- hosts: r9
  gather_facts: false
  connection: network_cli
  vars_files:
  - host_vars/r9
  roles:
    - routing
    - policy-based-rting

- hosts: r10
  gather_facts: false
  connection: network_cli
  vars_files:
  - host_vars/r10
  roles:
    - routing
    - policy-based-rting

- hosts: r1
  gather_facts: false
  connection: network_cli
  vars_files:
  - host_vars/r1
  roles:
    - core_routing

- hosts: r2
  gather_facts: false
  connection: network_cli
  vars_files:
  - host_vars/r2
  roles:
    - core_routing


- hosts: r3
  gather_facts: false
  connection: network_cli
  vars_files:
  - host_vars/r3
  roles:
    - dist_routing


- hosts: r4
  gather_facts: false
  connection: network_cli
  vars_files:
  - host_vars/r4
  roles:
    - dist_routing

- hosts: r5
  gather_facts: false
  connection: network_cli
  vars_files:
  - host_vars/r5
  roles:
    - dist_routing


- hosts: r6
  gather_facts: false
  connection: network_cli
  vars_files:
  - host_vars/r6
  roles:
    - dist_routing
