---
- name: show commands
  hosts: all
  gather_facts: false
  connection: network_cli
  become: yes

  tasks:
    - name: show commands
      ios_command:
        commands:
          - sh run 
          - show version
          - show ip interface brief
          - show interface description
 
      register: show_cmd_output
    - debug: var=show_cmd_output
