---
- name: Configuration commands
  hosts: all
  gather_facts: false
  connection: network_cli
  become: yes

  tasks:
    - name: interface_config
      ios_config:
        parents: interface loopback 0
        lines:
          - description test_ansible2.5


      register: config_output
    # to see only the commands that were entered by the playbook
    - debug: var=config_output.commands
    # to see all output
    - debug: var=config_output

    - name: routing_config
      ios_config:
        parents: router ospf 1
        lines:
          - passive-interface loopback0

      register: ospf_conf
    # to see only the ospf commands that were entered  
    - debug: var=ospf_conf.commands
    # to see all output 
    - debug: var=ospf_conf
