---
- hosts: ios-rtr
  gather_facts: no
  connection: local

  tasks:
   - name: show run 
     ios_command:
       commands:
         - show run
       host: "{{ inventory_hostname }}"
       username: cisco
       password: cisco
     register: config

   - name: save output to backups/
     copy:
       content: "{{ config.stdout[0] }}"
       dest: "backups/show_run_{{ inventory_hostname }}.txt"
